---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenit-port-forward-{{ .Release.Name }}
  namespace: debeando
spec:
  selector:
   matchLabels:
    app: zenit-port-forward
  replicas: 1
  template:
    metadata:
      labels:
        app: zenit-port-forward
    spec:
      containers:
        - name: zenit-port-forward-{{ .Release.Name }}
          image: debeando/zenit-port-forward
          resources:
            requests:
              cpu: "25m"
              memory: "12Mi"
            limits:
              cpu: "50m"
              memory: "16Mi"
          env:
            - name: "DEBUG"
              value: {{ default "false" .Values.debug | quote }}
            - name: "SSH_HOST"
              value: {{ .Values.ssh_host | quote }}
            - name: "SSH_PORT"
              value: {{ .Values.ssh_port | quote }}
            - name: "SSH_USER"
              value: {{ default "ec2-user" .Values.ssh_user | quote }}
            - name: "REMOTE_HOST"
              value: {{ .Values.remote_host | quote }}
            - name: "REMOTE_PORT"
              value: {{ default "3306" .Values.remote_port | quote }}
            - name: "LOCAL_PORT"
              value: {{ default "3306" .Values.local_port | quote }}
            - name: "SSH_KEY"
              valueFrom:
                secretKeyRef:
                  key:  SSH_KEY
                  name: {{ .Release.Name }}
