---
apiVersion: v1
kind: Service
metadata:
  name: zenit-port-forward-{{ .Release.Name }}
  namespace: debeando
  labels:
    app: zenit-port-forward
spec:
  type: NodePort
  selector:
    app: zenit-port-forward
  ports:
  - protocol: TCP
    port: {{ default "3306" .Values.local_port | quote }}
    targetPort: {{ default "3306" .Values.local_port | quote }}
