---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenit-agent-{{ .Release.Name }}
  namespace: debeando
spec:
  selector:
   matchLabels:
    app: zenit-agent-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: zenit-agent-mysql
    spec:
      containers:
        - name: zenit-agent-{{ .Release.Name }}
          image: debeando/zenit-agent-mysql
          resources:
            requests:
              cpu: "50m"
              memory: "16Mi"
            limits:
              cpu: "100m"
              memory: "16Mi"
          env:
            - name: "DEBUG"
              value: {{ default "false" .Values.debug | quote }}
            - name: "INTERVAL"
              value: {{ default "10" .Values.interval | quote }}
            - name: "HOSTNAME"
              value: {{ .Values.hostname | quote }}
            - name: "MYSQL_HOST"
              value: {{ .Values.mysql_host | quote }}
            - name: "MYSQL_PORT"
              value: {{ default "3306" .Values.mysql_port | quote }}
            - name: "MYSQL_USER"
              value: {{ .Values.mysql_user | quote }}
            - name: "MYSQL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key:  MYSQL_PASSWORD
                  name: {{ .Release.Name }}
