---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenit-agent-{{ .Release.Name }}
  namespace: debeando
spec:
  selector:
   matchLabels:
    app: zenit-agent-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: zenit-agent-mysql
    spec:
      containers:
        - name: zenit-agent-{{ .Release.Name }}
          image: debeando/zenit-agent-mysql
          env:          
            - name: "MYSQL_USER"
              value: {{ .Values.mysql_user }}
            - name: "MYSQL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key:  password
                  name: {{ .Release.Name }}
